services:
  _defaults:
    autowire: true
    autoconfigure: true

  Pageon\DoctrineDataGridBundle\DataGrid\DataGridFactory:

  Pageon\DoctrineDataGridBundle\Twig\DataGridExtension:
    tags: [ 'twig.extension' ]

  knp_paginator.subscriber.filtration:
    class: Pageon\DoctrineDataGridBundle\Filtration\FiltrationSubscriber
    tags:
      - { name: kernel.event_subscriber }

